fragment PostParts on Post {
  __typename
  title
  excerpt
  date
  coverImage
  author
  featured
  category
  body
}

fragment TestimonialParts on Testimonial {
  __typename
  clientName
  clientPosition
  company
  clientImage
  companyLogo
  testimonial
  rating
  featured
  date
}

fragment PageParts on Page {
  __typename
  title
  pageTitle
  subtitle
  description
  heroTitle
  heroSubtitle
  heroDescription
  ctaTitle
  ctaDescription
  ctaButtonText
  stats {
    __typename
    label
    value
    description
  }
  servicesSectionTag
  servicesSectionTitle
  servicesSectionDescription
  services {
    __typename
    title
    description
    icon
    color
  }
  processSectionTag
  processSectionTitle
  processSectionDescription
  processSteps {
    __typename
    number
    title
    description
    icon
    color
  }
  featuresSectionTag
  featuresSectionTitle
  featuresSectionDescription
  features {
    __typename
    title
    description
    icon
    gradient
  }
  aboutTitle
  aboutDescription
  story
  mission
  values {
    __typename
    title
    description
    icon
  }
  team {
    __typename
    name
    position
    bio
    image
  }
  contactSectionTitle
  contactSectionDescription
  email
  phone
  address
  officeHours
  socialMedia {
    __typename
    twitter
    linkedin
    instagram
  }
  footerBrandName
  footerTagline
  body
}
